name: CI

on: [push]

jobs:
  build:
    name: Demo build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run lint
      run: yarn lint
    - name: Run test
      run: yarn test
    - name: Prepare git
      run: |
        touch ./id_rsa
        chmod 700 ./id_rsa
        echo "${{ secrets.BOT_SSH_KEY }}" > id_rsa
        eval $(ssh-agent -s)
        ssh-add ./id_rsa
    - name: run demo build
      run: node ./bin/demo-build.js
    - name: Publish storybook
      run: |
        cd ./storybook-demo
        git push -q -f "https://alfa-bot:${{ secrets.BOT_AUTH_TOKEN }}@github.com/feankoalex/core-components.git" master:gh-pages
    - name: Echo ls
      run: |
        ls
    - name: Cleanup work dir
      run: |
        cd ../
        rm -rf storybook-demo
