name: CI

on: [push]

jobs:
  build:
    name: Demo build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: yarn
    - name: run lint
      run: yarn lint
    - name: run test
      run: yarn test
    # - name: run demo build
    #   run: node ./bin/scripts/demo.js
