name: CI

on: [push]

jobs:
  build:
    name: Demo build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint

      # - name: Run test
      #   run: yarn test

      # - name: Prepare git
      #   run: |
      #     touch ./id_rsa
      #     chmod 700 ./id_rsa
      #     echo "${{ secrets.BOT_SSH_KEY }}" > id_rsa
      #     eval $(ssh-agent -s)
      #     ssh-add ./id_rsa

      - name: Run build
        run: node ./bin/demo-build.js

      - name: Publish storybook
        run: |
          cd ./storybook-demo
          git push -q -f "https://alfa-bot:${{ secrets.BOT_AUTH_TOKEN }}@github.com/FenkoAlex/core-components.git" master:gh-pages

      - name: Storybook deployed to
        run: |
          echo ${{ steps.step_one.outputs.gitPagesUrl }}
